describe('First Case', () => {
  it('Visit site and log i', () => {
    cy.visit('http://mavr.kemsu.ru/')
    cy.wait(1000)
    cy.get('[id="login1"]').type('ADMIN').should('have.value', 'ADMIN')
    cy.wait(1000)
    cy.get('[id="login2"]').type('ADMIN').should('have.value', 'ADMIN')
    cy.wait(1000)
    cy.get('[class="login-button"]').click()
  })
  it('Visit report managers and generate a new report', () => {
    cy.get('[id="mo"]').click()
    cy.wait(1000)
    cy.get('[id="okol"]').click()
    cy.wait(1000)
    cy.get(':nth-child(2) > .OClNORMBlockIn > :nth-child(2) > .ListPrText2').click()
    cy.wait(1000)
    cy.get('.profile-button2').click()
    cy.wait(1000)
  })
  it('Visit work with classes button', () => {
    cy.get('[id="o2"]').click()
    cy.wait(1000)
    cy.get('[id="reportQuantity"]').click()
    cy.wait(1000)
    cy.get('[id="reportSexMale"]').click()
    cy.wait(1000)
    cy.get('[id="reportFamilyAll"]').click()
    cy.wait(1000)
    cy.get('[id="reportFamilyMaterialConditionMiddle"]').click()
    cy.wait(1000)
    cy.get('[id="reportFamilyEducationMiddle"]').click()
    cy.wait(1000)
    cy.get(':nth-child(5) > :nth-child(5) > .ListPrText2').click()
    cy.wait(1000)
    cy.get(':nth-child(2) > :nth-child(8) > :nth-child(3) > .ListPrText2').click()
    cy.wait(1000)
    cy.get('.profile-button2').click()
    cy.wait(1000)
  })
})