describe('Second Case', () => {
  it('Visit site and log in', () => {
    cy.visit('http://mavr.kemsu.ru/')
    cy.wait(1000)
    cy.get('[id="login1"]').type('ADMIN').should('have.value', 'ADMIN')
    cy.wait(1000)
    cy.get('[id="login2"]').type('ADMIN').should('have.value', 'ADMIN')
    cy.wait(1000)
    cy.get('[class="login-button"]').click()
    cy.wait(1000)
  })
  it('Create new profile', () => {
    cy.visit('http://mavr.kemsu.ru/control_users')
    cy.wait(1000)
    Cypress.on('uncaught:exception', (err, runnable) => {
      return false
    })
    cy.get('[id="newUserLogin"]').type('Vasya_Pupkin').should('have.value', 'Vasya_Pupkin')
    cy.wait(1000)
    cy.get('[id="newUserPassword"]').type('123').should('have.value', '123')
    cy.wait(1000)
    cy.get('[id="newUserLastname"]').type('Пупкин').should('have.value', 'Пупкин')
    cy.wait(1000)
    cy.get('[id="newUserName"]').type('Василий').should('have.value', 'Василий')
    cy.wait(1000)
    cy.get('[id="newUserMiddlename"]').type('Васильевич').should('have.value', 'Васильевич')
    cy.wait(1000)
    cy.get('[id="newUserComment"]').type('No comments').should('have.value', 'No comments')
    cy.wait(1000)
    cy.get('[id="newUserRole"]').select('USER')
    cy.wait(1000)
    cy.get(':nth-child(1) > .text-main > .ListPr4 > #container > .profile-button2').click()
    cy.wait(1000)
  })
  it('Create new class', () => {
    Cypress.on('uncaught:exception', (err, runnable) => {
      return false
    })
    cy.get('[id="controlClasses"]').click()
    cy.wait(1000)
    cy.get('[id="createClassNumber"]').type('9').should('have.value', '9')
    cy.wait(1000)
    cy.get('[id="createClassLetter"]').type('a').should('have.value', 'a')
    cy.wait(1000)
    cy.get(':nth-child(1) > .text-main > .ListPr4 > #container > .profile-button2').click()
    cy.wait(1000)
  })
  it('Create new event', () => {
    cy.get('[id="controlEvents"]').click()
    cy.wait(1000)
    cy.get('[id="createProgramNameInput"]').type('New event').should('have.value', 'New event')
    cy.wait(1000)
    cy.get('[id="createProgramDescriprtionInput"]').type('Some description').should('have.value', 'Some description')
    cy.wait(1000)
    cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > #container > .profile-button2').click()
    cy.wait(1000)
  })
  it('Create new plan', () => {
    cy.get('[id="controlPlans"]').click()
    cy.wait(1000)
    cy.get('[id="createYearPlanInputYear"]').type('2022').should('have.value', '2022')
    cy.wait(1000)
    cy.get('[id="createYearPlanInputGoalsOfEducationalWork"]').type('New goal').should('have.value', 'New goal')
    cy.wait(1000)
    cy.get('[id="createYearPlanInputTargetPriorities14"]').type('1-4 classes priorities').should('have.value', '1-4 classes priorities')
    cy.wait(1000)
    cy.get('[id="createYearPlanInputTasks14"]').type('1-4 classes tasks').should('have.value', '1-4 classes tasks')
    cy.wait(1000)
    cy.get('[id="createYearPlanInputTargetPriorities59"]').type('5-9 classes priorities').should('have.value', '5-9 classes priorities')
    cy.wait(1000)
    cy.get('[id="createYearPlanInputTasks59"]').type('5-9 classes tasks').should('have.value', '5-9 classes tasks')
    cy.wait(1000)
    cy.get('[id="createYearPlanInputTargetPriorities1011"]').type('10-11 classes priorities').should('have.value', '10-11 classes priorities')
    cy.wait(1000)
    cy.get('[id="createYearPlanInputTasks1011"]').type('10-11 classes tasks').should('have.value', '10-11 classes tasks')
    cy.wait(1000)
    cy.get('.profile-button2').click()
    cy.wait(1000)
  })
})